/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatInboxRouteImport } from './routes/_chat.inbox'
import { Route as ChatAutomationsRouteImport } from './routes/_chat.automations'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatTasksIndexRouteImport } from './routes/_chat.tasks.index'
import { Route as ChatStudioIndexRouteImport } from './routes/_chat.studio.index'
import { Route as ChatPullRequestsIndexRouteImport } from './routes/_chat.pull-requests.index'
import { Route as ChatKanbanIndexRouteImport } from './routes/_chat.kanban.index'
import { Route as ChatHubsIndexRouteImport } from './routes/_chat.hubs.index'
import { Route as ChatGroupsIndexRouteImport } from './routes/_chat.groups.index'
import { Route as ChatAutomationsIndexRouteImport } from './routes/_chat.automations.index'
import { Route as ChatKanbanProjectIdRouteImport } from './routes/_chat.kanban.$projectId'
import { Route as ChatAutomationsAutomationIdRouteImport } from './routes/_chat.automations.$automationId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatInboxRoute = ChatInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsRoute = ChatAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatTasksIndexRoute = ChatTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatStudioIndexRoute = ChatStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsIndexRoute = ChatPullRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatPullRequestsRoute,
} as any)
const ChatKanbanIndexRoute = ChatKanbanIndexRouteImport.update({
  id: '/kanban/',
  path: '/kanban/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatHubsIndexRoute = ChatHubsIndexRouteImport.update({
  id: '/hubs/',
  path: '/hubs/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatGroupsIndexRoute = ChatGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsIndexRoute = ChatAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAutomationsRoute,
} as any)
const ChatKanbanProjectIdRoute = ChatKanbanProjectIdRouteImport.update({
  id: '/kanban/$projectId',
  path: '/kanban/$projectId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsAutomationIdRoute =
  ChatAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => ChatAutomationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/automations': typeof ChatAutomationsRouteWithChildren
  '/inbox': typeof ChatInboxRoute
  '/plugins': typeof ChatPluginsRoute
  '/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/automations/': typeof ChatAutomationsIndexRoute
  '/groups/': typeof ChatGroupsIndexRoute
  '/hubs/': typeof ChatHubsIndexRoute
  '/kanban/': typeof ChatKanbanIndexRoute
  '/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/studio/': typeof ChatStudioIndexRoute
  '/tasks/': typeof ChatTasksIndexRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/inbox': typeof ChatInboxRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/automations': typeof ChatAutomationsIndexRoute
  '/groups': typeof ChatGroupsIndexRoute
  '/hubs': typeof ChatHubsIndexRoute
  '/kanban': typeof ChatKanbanIndexRoute
  '/pull-requests': typeof ChatPullRequestsIndexRoute
  '/studio': typeof ChatStudioIndexRoute
  '/tasks': typeof ChatTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/automations': typeof ChatAutomationsRouteWithChildren
  '/_chat/inbox': typeof ChatInboxRoute
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/_chat/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/_chat/automations/': typeof ChatAutomationsIndexRoute
  '/_chat/groups/': typeof ChatGroupsIndexRoute
  '/_chat/hubs/': typeof ChatHubsIndexRoute
  '/_chat/kanban/': typeof ChatKanbanIndexRoute
  '/_chat/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/_chat/studio/': typeof ChatStudioIndexRoute
  '/_chat/tasks/': typeof ChatTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/automations'
    | '/inbox'
    | '/plugins'
    | '/pull-requests'
    | '/settings'
    | '/automations/$automationId'
    | '/kanban/$projectId'
    | '/automations/'
    | '/groups/'
    | '/hubs/'
    | '/kanban/'
    | '/pull-requests/'
    | '/studio/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/inbox'
    | '/plugins'
    | '/settings'
    | '/'
    | '/automations/$automationId'
    | '/kanban/$projectId'
    | '/automations'
    | '/groups'
    | '/hubs'
    | '/kanban'
    | '/pull-requests'
    | '/studio'
    | '/tasks'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/automations'
    | '/_chat/inbox'
    | '/_chat/plugins'
    | '/_chat/pull-requests'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/automations/$automationId'
    | '/_chat/kanban/$projectId'
    | '/_chat/automations/'
    | '/_chat/groups/'
    | '/_chat/hubs/'
    | '/_chat/kanban/'
    | '/_chat/pull-requests/'
    | '/_chat/studio/'
    | '/_chat/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/inbox': {
      id: '/_chat/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ChatInboxRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations': {
      id: '/_chat/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof ChatAutomationsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/tasks/': {
      id: '/_chat/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof ChatTasksIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/studio/': {
      id: '/_chat/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof ChatStudioIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests/': {
      id: '/_chat/pull-requests/'
      path: '/'
      fullPath: '/pull-requests/'
      preLoaderRoute: typeof ChatPullRequestsIndexRouteImport
      parentRoute: typeof ChatPullRequestsRoute
    }
    '/_chat/kanban/': {
      id: '/_chat/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof ChatKanbanIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/hubs/': {
      id: '/_chat/hubs/'
      path: '/hubs'
      fullPath: '/hubs/'
      preLoaderRoute: typeof ChatHubsIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/groups/': {
      id: '/_chat/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof ChatGroupsIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations/': {
      id: '/_chat/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof ChatAutomationsIndexRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
    '/_chat/kanban/$projectId': {
      id: '/_chat/kanban/$projectId'
      path: '/kanban/$projectId'
      fullPath: '/kanban/$projectId'
      preLoaderRoute: typeof ChatKanbanProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations/$automationId': {
      id: '/_chat/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof ChatAutomationsAutomationIdRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
  }
}

interface ChatAutomationsRouteChildren {
  ChatAutomationsAutomationIdRoute: typeof ChatAutomationsAutomationIdRoute
  ChatAutomationsIndexRoute: typeof ChatAutomationsIndexRoute
}

const ChatAutomationsRouteChildren: ChatAutomationsRouteChildren = {
  ChatAutomationsAutomationIdRoute: ChatAutomationsAutomationIdRoute,
  ChatAutomationsIndexRoute: ChatAutomationsIndexRoute,
}

const ChatAutomationsRouteWithChildren = ChatAutomationsRoute._addFileChildren(
  ChatAutomationsRouteChildren,
)

interface ChatPullRequestsRouteChildren {
  ChatPullRequestsIndexRoute: typeof ChatPullRequestsIndexRoute
}

const ChatPullRequestsRouteChildren: ChatPullRequestsRouteChildren = {
  ChatPullRequestsIndexRoute: ChatPullRequestsIndexRoute,
}

const ChatPullRequestsRouteWithChildren =
  ChatPullRequestsRoute._addFileChildren(ChatPullRequestsRouteChildren)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatAutomationsRoute: typeof ChatAutomationsRouteWithChildren
  ChatInboxRoute: typeof ChatInboxRoute
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatPullRequestsRoute: typeof ChatPullRequestsRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatKanbanProjectIdRoute: typeof ChatKanbanProjectIdRoute
  ChatGroupsIndexRoute: typeof ChatGroupsIndexRoute
  ChatHubsIndexRoute: typeof ChatHubsIndexRoute
  ChatKanbanIndexRoute: typeof ChatKanbanIndexRoute
  ChatStudioIndexRoute: typeof ChatStudioIndexRoute
  ChatTasksIndexRoute: typeof ChatTasksIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatAutomationsRoute: ChatAutomationsRouteWithChildren,
  ChatInboxRoute: ChatInboxRoute,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatPullRequestsRoute: ChatPullRequestsRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatKanbanProjectIdRoute: ChatKanbanProjectIdRoute,
  ChatGroupsIndexRoute: ChatGroupsIndexRoute,
  ChatHubsIndexRoute: ChatHubsIndexRoute,
  ChatKanbanIndexRoute: ChatKanbanIndexRoute,
  ChatStudioIndexRoute: ChatStudioIndexRoute,
  ChatTasksIndexRoute: ChatTasksIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
