// FILE: projectEmoji.ts
// Purpose: The emoji the project picker offers, with search words. Curated and bundled so the
//          picker works offline; any other emoji can still be typed or pasted into the search.
// Layer: Web lib (data)

export interface ProjectEmojiOption {
  readonly emoji: string;
  readonly keywords: string;
}

function entries(list: ReadonlyArray<readonly [string, string]>): ProjectEmojiOption[] {
  return list.map(([emoji, keywords]) => ({ emoji, keywords }));
}

export const PROJECT_EMOJI_OPTIONS: ReadonlyArray<ProjectEmojiOption> = entries([
  // Work and making things
  ["🚀", "rocket launch ship startup"],
  ["💡", "idea light bulb"],
  ["⚡", "lightning fast speed power"],
  ["🔥", "fire hot trending"],
  ["✨", "sparkles magic new shiny"],
  ["⭐", "star favorite"],
  ["🎯", "target goal focus"],
  ["🏆", "trophy win award"],
  ["💻", "laptop computer code dev"],
  ["🖥️", "desktop computer monitor"],
  ["⌨️", "keyboard typing"],
  ["🧑‍💻", "developer coder programmer"],
  ["🤖", "robot bot ai agent"],
  ["🧠", "brain mind ai thinking"],
  ["🛠️", "tools hammer wrench build"],
  ["🔧", "wrench fix settings"],
  ["⚙️", "gear settings config"],
  ["🧪", "test tube science lab experiment"],
  ["🔬", "microscope science research"],
  ["🧩", "puzzle plugin piece"],
  ["🐛", "bug debug issue"],
  ["📦", "package box shipping release"],
  ["🗂️", "folders files organize"],
  ["📁", "folder directory project"],
  ["📝", "memo notes writing"],
  ["📚", "books library docs learning"],
  ["📖", "book reading docs"],
  ["✏️", "pencil edit draft"],
  ["🖊️", "pen writing sign"],
  ["📊", "chart bar stats analytics"],
  ["📈", "chart growth up trend"],
  ["💰", "money bag finance"],
  ["💵", "dollar cash money"],
  ["💳", "card payment billing"],
  ["🏦", "bank finance"],
  ["💼", "briefcase work business job"],
  ["📅", "calendar date schedule plan"],
  ["⏰", "alarm clock time"],
  ["📌", "pin pinned important"],
  ["🔒", "lock private security"],
  ["🔑", "key access password"],
  ["🛡️", "shield security protect"],
  ["🌐", "globe web internet"],
  ["☁️", "cloud hosting server"],
  ["🗄️", "cabinet database storage"],
  ["📱", "phone mobile app ios android"],
  ["🎨", "palette art design paint"],
  ["🖌️", "brush paint design"],
  ["📐", "ruler triangle design geometry"],
  ["📷", "camera photo picture"],
  ["🎬", "movie film clapper video"],
  ["🎥", "video camera film"],
  ["🎵", "music note song"],
  ["🎧", "headphones music audio podcast"],
  ["🎙️", "microphone podcast voice"],
  ["🎮", "game controller gaming play"],
  ["🎲", "dice game random"],
  ["🧸", "teddy bear toy kids"],
  ["🎁", "gift present"],
  ["🎉", "party celebration tada"],
  ["📣", "megaphone marketing announce"],
  ["💬", "chat speech message"],
  ["✉️", "envelope email mail"],
  ["🛒", "cart shopping store ecommerce"],
  ["🏷️", "tag label price"],
  // Study, health, and life
  ["🎓", "graduation cap school study education"],
  ["🏫", "school education"],
  ["🧮", "abacus math"],
  ["🔭", "telescope astronomy space"],
  ["⚖️", "scale law justice legal"],
  ["🩺", "stethoscope health doctor medical"],
  ["💊", "pill medicine health"],
  ["❤️", "heart love red"],
  ["🧘", "yoga meditation wellness calm"],
  ["🏋️", "weight lifting gym fitness"],
  ["🏃", "running run sport"],
  ["⚽", "soccer football sport"],
  ["🏀", "basketball sport"],
  ["🚴", "cycling bike sport"],
  ["✈️", "airplane travel flight trip"],
  ["🗺️", "map travel world"],
  ["🧭", "compass direction explore"],
  ["🏔️", "mountain nature hiking"],
  ["🏖️", "beach vacation holiday"],
  ["🏠", "house home personal"],
  ["🏢", "office building company"],
  ["🚗", "car auto drive"],
  ["☕", "coffee tea drink break"],
  ["🍕", "pizza food"],
  ["🍔", "burger food"],
  ["🍎", "apple fruit food"],
  ["🥑", "avocado food healthy"],
  ["🍳", "cooking egg food recipe"],
  ["🍷", "wine drink"],
  ["🍰", "cake dessert"],
  // Nature and animals
  ["🌱", "seedling plant grow green"],
  ["🌿", "herb leaf plant nature"],
  ["🌳", "tree nature forest"],
  ["🌵", "cactus plant desert"],
  ["🌸", "cherry blossom flower spring"],
  ["🌻", "sunflower flower summer"],
  ["🍀", "clover luck green"],
  ["🌊", "wave ocean sea water"],
  ["🌍", "earth globe world planet"],
  ["🌙", "moon night"],
  ["☀️", "sun sunny day"],
  ["🌈", "rainbow colors"],
  ["❄️", "snowflake winter cold"],
  ["🐶", "dog puppy pet animal"],
  ["🐱", "cat kitten pet animal"],
  ["🦊", "fox animal"],
  ["🐻", "bear animal"],
  ["🐼", "panda animal"],
  ["🦁", "lion animal"],
  ["🐸", "frog animal"],
  ["🐙", "octopus animal sea"],
  ["🦋", "butterfly insect nature"],
  ["🐝", "bee insect honey"],
  ["🦄", "unicorn magic"],
  ["🐳", "whale docker sea animal"],
  ["🦀", "crab rust sea animal"],
  ["🐍", "snake python animal"],
  ["🐘", "elephant php animal"],
  // Faces and hands
  ["😀", "grin smile happy face"],
  ["😎", "cool sunglasses face"],
  ["🤓", "nerd glasses face"],
  ["🤔", "thinking face"],
  ["🥳", "party face celebrate"],
  ["👻", "ghost spooky"],
  ["👽", "alien space"],
  ["👀", "eyes look watch"],
  ["👍", "thumbs up ok yes"],
  ["👋", "wave hello hi"],
  ["🙌", "raised hands celebrate"],
  ["💪", "muscle strong flex"],
]);
